server.port=8081
server.compression=on
server.compressableMimeTypes=application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
server.compression.min-response-size=1024
server.http2.enabled=true
spring.resources.cache.cachecontrol.max-age=86400
spring.resources.cache.cachecontrol.cache-private=true
spring.resources.cache.cachecontrol.cache-public=false
logging.file.name = /home/karl/logs/web/spring-boot.log
