# Update docs/vh.html when this value changes.
# Also, execute:
# ant version
# to update the pom.xml files with the new version.
PV=1.0.9

# Dependencies, also update shoring/pom.xml
FXV=18-ea+7
GSONV=2.8.8
LOG4J2V=2.14.1

# Static content staging area.  If this changes, 
#  also update loadprops.cmd.
HTTP_HOME=./temp/www80/html
