# Update docs/vh.html when this value changes.
# Also, execute:
# ant version
# to update the pom.xml files with the new version.
PV=1.1

# Dependencies, also update shoring/pom.xml
FXV=19-ea+2
GSONV=2.9.0
LOG4J2V=2.17.1
KV=1.6.0

# Static content staging area. 
HTTP_HOME=./temp/www80/html

